# Generated by Django 5.2.1 on 2025-05-31 06:59

import bakery_app.utils.upload_file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_app', '0003_alter_news_category_alter_news_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='src',
        ),
        migrations.AddField(
            model_name='slide',
            name='image',
            field=models.ImageField(default=None, upload_to=bakery_app.utils.upload_file.UploadToUUID('slide/')),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slide',
            name='link',
            field=models.CharField(help_text='點擊圖片後導向的連結', max_length=10000),
        ),
        migrations.AlterField(
            model_name='slide',
            name='sub_title',
            field=models.CharField(blank=True, help_text='幻燈片的副標題', max_length=30),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(blank=True, help_text='幻燈片的標題', max_length=20),
        ),
    ]
