# Generated by Django 5.2.1 on 2025-05-31 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_app', '0004_remove_slide_src_slide_image_alter_slide_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name': '輪播圖', 'verbose_name_plural': '輪播圖'},
        ),
        migrations.AlterField(
            model_name='slide',
            name='link',
            field=models.CharField(blank=True, help_text='點擊圖片後導向的連結', max_length=1000),
        ),
        migrations.AlterField(
            model_name='slide',
            name='sub_title',
            field=models.CharField(blank=True, help_text='輪播圖的副標題', max_length=30),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(blank=True, help_text='輪播圖的標題', max_length=20),
        ),
    ]
