# Generated by Django 5.2.1 on 2025-05-31 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_app', '0005_alter_slide_options_alter_slide_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', '貨到付款'), ('linepay', 'Line Pay')], default='cod', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', '未付款'), ('paid', '已付款'), ('refunded', '已退款')], default='unpaid', max_length=10),
        ),
    ]
