# Generated by Django 5.2.1 on 2025-05-31 07:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_app', '0006_order_payment_method_order_payment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '訂單', 'verbose_name_plural': '訂單'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': '訂單明細', 'verbose_name_plural': '訂單明細'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(default=1, max_length=100, validators=[django.core.validators.EmailValidator(message='請輸入有效的 Email 地址')], verbose_name='顧客 Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default=1, max_length=100, verbose_name='顧客姓名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(default=1, max_length=20, validators=[django.core.validators.RegexValidator(message='請輸入正確的手機號碼（例如：0912345678 或 +886912345678）', regex='^\\+?886\\d{9}$|^09\\d{8}$')], verbose_name='顧客電話'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', '貨到付款'), ('linepay', 'Line Pay')], default='cod', max_length=10, verbose_name='付款方式'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', '未付款'), ('paid', '已付款'), ('refunded', '已退款')], default='unpaid', max_length=10, verbose_name='付款狀態'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='總金額'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bakery_app.order', verbose_name='所屬訂單'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='單價'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery_app.product', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='數量'),
        ),
    ]
