# Generated by Django 5.2.1 on 2025-05-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_app', '0007_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': '最新消息', 'verbose_name_plural': '最新消息'},
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(max_length=10, verbose_name='分類'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='news',
            name='release_date',
            field=models.DateTimeField(verbose_name='發布日期'),
        ),
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=models.TextField(max_length=50, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=30, verbose_name='標題'),
        ),
    ]
