# Generated by Django 5.2.1 on 2025-05-31 07:53

import bakery_app.utils.upload_file
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_app', '0008_alter_news_options_alter_news_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name': '商品類別', 'verbose_name_plural': '商品類別'},
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='商品說明'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=bakery_app.utils.upload_file.UploadToUUID('products/'), verbose_name='商品圖片'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='商品名稱'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=6, verbose_name='價格'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bakery_app.producttype', verbose_name='商品類別'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='description',
            field=models.TextField(blank=True, verbose_name='類別說明'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='image',
            field=models.ImageField(upload_to=bakery_app.utils.upload_file.UploadToUUID('product_types/'), verbose_name='類別圖片'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='類別名稱'),
        ),
    ]
