# Generated by Django 5.2.1 on 2025-05-31 07:55

import bakery_app.utils.upload_file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_app', '0009_alter_product_options_alter_producttype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(upload_to=bakery_app.utils.upload_file.UploadToUUID('slide/'), verbose_name='圖片'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='link',
            field=models.CharField(blank=True, help_text='點擊圖片後導向的連結', max_length=1000, verbose_name='導向連結'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='sub_title',
            field=models.CharField(blank=True, help_text='輪播圖的副標題', max_length=30, verbose_name='副標題'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(blank=True, help_text='輪播圖的標題', max_length=20, verbose_name='標題'),
        ),
    ]
